# Generated by Django 3.1.10 on 2021-05-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210507_2307'),
        ('property', '0003_auto_20210531_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='tenants',
            field=models.ManyToManyField(related_name='spaces', to='user.Tenant'),
        ),
    ]
